const test=require('node:test'),assert=require('node:assert/strict');
const {create,resolveVars}=require('../typography-trace.js');
const style=object=>({cssText:Object.entries(object).map(([k,v])=>`${k}: ${v};`).join(''),getPropertyValue:p=>(object[p]||'').replace(/\s*!important$/,''),getPropertyPriority:p=>object[p]?.endsWith('!important')?'important':''});
const node=(name,parent,computed={},inline={})=>({localName:name,parentElement:parent,style:style(inline),matches:s=>s===name,computed:{'font-size':'14px','font-weight':'400','color':'white','--size':'14px',...computed}});
function env(rules=[],extra={}){return {rules:rules.map(([selector,values])=>({selector,style:style(values),source:'test.css'})),known:new Set(['--size']),opaque:false,getStyle:n=>({...n.computed,getPropertyValue:p=>n.computed[p]||''}),specificity:()=>[0,0,0,1],split:s=>s.split(','),compare:(a,b)=>a.reduce((result,n,i)=>result||n-b[i],0),makeStyle:()=>{throw Error('Font expansion is verified in browser');},...extra};}
test('tracks inherited tokens from actual text descendants',()=>{const parent=node('div',null),child=node('span',parent);const result=create(env([['div',{'font-size':'var(--size)'}]])).trace(child,'font-size');assert.equal(result.kind,'token');assert.equal(result.inherited,true);assert.equal(result.selector,'div');});
test('inline literal overrides shared token; important beats normal inline',()=>{const el=node('span',null,{}, {'font-size':'18px'});assert.equal(create(env([['span',{'font-size':'var(--size)'}]])).trace(el,'font-size').kind,'hard');assert.equal(create(env([['span',{'font-size':'var(--size) !important'}]])).trace(el,'font-size').kind,'token');});
test('explicit inherit and unset trace their parent',()=>{for(const value of ['inherit','unset']){const parent=node('div',null),child=node('span',parent,{}, {'font-size':value});assert.equal(create(env([['div',{'font-size':'var(--size)'}]])).trace(child,'font-size').kind,'token');}});
test('missing author declarations are defaults, inaccessible cascade is not',()=>{const el=node('div',null);assert.equal(create(env()).trace(el,'font-size').kind,'default');assert.equal(create(env([], {opaque:true})).trace(el,'font-size').kind,'unknown');});
test('unknown tokens and complex cascade retain uncertainty',()=>{const el=node('span',null,{'--local':'14px'});assert.equal(create(env([['span',{'font-size':'var(--local)'}]])).trace(el,'font-size').kind,'unknown');assert.equal(create(env([['span',{'font-size':'var(--size)'}]],{specificity:()=>null})).trace(el,'font-size').kind,'unknown');});
test('literal fallback is not claimed as tokenized',()=>{const el=node('span',null);const result=create(env([['span',{'color':'var(--missing, red)'}]])).trace(el,'color');assert.equal(result.kind,'hard');assert.match(result.reason,/fallback/);});
test('nested variables, fallbacks and cycles are explicit',()=>{const cs={getPropertyValue:p=>({'--a':'var(--b)','--b':'14px','--cycle':'var(--cycle)'}[p]||'')};assert.equal(resolveVars('var(--a)',cs).value,'14px');assert.equal(resolveVars('var(--none, var(--b))',cs).value.trim(),'14px');assert.equal(resolveVars('var(--cycle)',cs).error,true);});
test('native controls report defaults only when no ancestor author source competes',()=>{const parent=node('div',null),button=node('button',parent);assert.equal(create(env()).trace(button,'font-weight').kind,'default');assert.equal(create(env([['div',{'font-weight':'600'}]])).trace(button,'font-weight').kind,'unknown');});
test('active transitions and layers do not produce a confident source verdict',()=>{const el=node('span',null);el.getAnimations=()=>[{playState:'running'}];assert.equal(create(env()).trace(el,'color').kind,'unknown');delete el.getAnimations;const e=env([['span',{'color':'red'}]]);e.rules[0].uncertain=true;assert.equal(create(e).trace(el,'color').kind,'unknown');});
