(() => {
  const part=new URLSearchParams(location.search).get('part')||'modal',host=document.getElementById('pattern');
  if(part==='modal'){
    host.innerHTML='<div class="ds-stack"><h1>Bounded task</h1><p>A modal retains the current screen and uses native focus and Escape behavior.</p><button class="ds-btn ds-btn--primary" id="open-dialog">Open mock dialog</button><output aria-live="polite" id="dialog-result"></output></div><dialog class="lab-dialog" id="dialog"><form method="dialog" class="ds-stack ds-stack--sections"><h2>Schedule a review</h2><div class="ds-field"><label class="ds-field-label" for="review-name">Title</label><input class="ds-input" id="review-name" value="Northstar review"></div><div class="ds-row ds-row--end"><button class="ds-btn ds-btn--secondary" value="cancel">Cancel</button><button class="ds-btn ds-btn--primary" value="scheduled">Schedule mock review</button></div></form></dialog>';
    const dialog=document.getElementById('dialog');document.getElementById('open-dialog').onclick=()=>dialog.showModal();dialog.onclose=()=>{document.getElementById('dialog-result').textContent=dialog.returnValue==='scheduled'?'Mock review scheduled. No data was saved.':'Dialog closed';};
  }else if(part==='settings'){
    host.innerHTML='<div class="ds-stack ds-stack--sections"><header><h1>Workspace settings</h1><p>Full-page task · cold-loadable URL</p></header><div class="lab-settings"><nav aria-label="Settings sections"><a href="#general">General</a><a href="#notifications">Notifications</a></nav><div class="ds-stack ds-stack--sections"><section class="ds-card ds-stack" id="general"><h2>General</h2><div class="ds-field"><label class="ds-field-label" for="workspace-name">Workspace name</label><input class="ds-input" id="workspace-name" value="Atlas"></div></section><section class="ds-card ds-stack" id="notifications"><h2>Notifications</h2><label><input type="checkbox" checked> Weekly mock digest</label></section></div></div></div>';
  }else{
    host.innerHTML='<div class="ds-stack"><h1>Two-pane workspace</h1><p>Resize within 40–70%. Keyboard: Left/Right, Home/End. Panes stack on narrow screens.</p><div class="lab-pane-layout"><section class="lab-pane" id="editor"><h2>Editor</h2><div class="ds-field"><label class="ds-field-label" for="preview-title">Heading</label><input class="ds-input" id="preview-title" value="A clear starting point"></div></section><div class="lab-resizer" role="separator" tabindex="0" aria-label="Pane width" aria-orientation="vertical" aria-valuemin="40" aria-valuemax="70" aria-valuenow="55"></div><section class="lab-pane"><h2 id="live-title">A clear starting point</h2><p>Both surfaces remain visible.</p></section></div></div>';
    const editor=document.getElementById('editor'),resizer=host.querySelector('.lab-resizer');let value=55;
    function set(next){value=Math.max(40,Math.min(70,next));editor.style.flex='0 0 '+value+'%';resizer.setAttribute('aria-valuenow',String(Math.round(value)));}
    resizer.onkeydown=e=>{const next={ArrowLeft:value-2,ArrowRight:value+2,Home:40,End:70}[e.key];if(next!==undefined){e.preventDefault();set(next);}};
    resizer.onpointerdown=e=>{resizer.setPointerCapture(e.pointerId);};resizer.onpointermove=e=>{if(!resizer.hasPointerCapture(e.pointerId))return;const bounds=resizer.parentElement.getBoundingClientRect();set((e.clientX-bounds.left)/bounds.width*100);};resizer.onpointerup=e=>{if(resizer.hasPointerCapture(e.pointerId))resizer.releasePointerCapture(e.pointerId);};
    document.getElementById('preview-title').oninput=e=>{document.getElementById('live-title').textContent=e.target.value;};set(value);
  }
})();
