(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TitanActions=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const Icons=typeof module==='object'&&module.exports?require('../icons/runtime.js'):globalThis.TitanIcons;
 'use strict';
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const label=value=>{if(typeof value!=='string'||!value.trim())throw Error('An accessible label is required');return esc(value);};
 const icon=(id,color)=>Icons.render(id,color);
 const toggleArtwork=(id,color,cls)=>Icons.render(id,color).replace(/^<(svg|img)/,'<$1 class="'+cls+'"');
 const disabled=value=>value?' disabled':'';
 function iconButton(opts={}){const legacy=opts.variant;opts={...opts};if(['window','dark-compact'].includes(legacy)){opts.variant='dark';opts.iconSize??=legacy==='window'?18:16;}if(opts.iconSize!==undefined&&![16,18,20,24].includes(opts.iconSize))throw Error('Supported icon sizes: 16, 18, 20, 24');if(!opts.icon)throw Error('An icon is required');if(opts.size!==undefined&&![32,40].includes(opts.size))throw Error('Supported icon button sizes: 32, 40');const toggle=opts.variant==='toggle';if(toggle){if(opts.size!==undefined)throw Error('Toggle icon buttons use the fixed 24px size');if(typeof opts.pressed!=='boolean')throw Error('A toggle icon button requires an explicit pressed state');if(!opts.pressedIcon)throw Error('A toggle icon button requires a pressedIcon');}return '<button type="button" class="titan-icon-button'+(opts.size===40?' titan-icon-button--40':'')+(['composer','dark','dark-quiet','compact','toggle'].includes(opts.variant)?' titan-icon-button--'+opts.variant:'')+'"'+(opts.iconSize?' style="--titan-icon-button-artwork-size:var(--titan-icon-size-'+opts.iconSize+')"':'')+' data-action="main" aria-label="'+label(opts.label)+'" title="'+esc(opts.label)+'"'+disabled(opts.disabled)+(typeof opts.pressed==='boolean'?' aria-pressed="'+opts.pressed+'"':'')+'>'+(toggle?toggleArtwork(opts.icon,opts.iconColor,'titan-icon-button__icon-off')+toggleArtwork(opts.pressedIcon,opts.iconColor,'titan-icon-button__icon-on'):icon(opts.icon,opts.iconColor))+'</button>';}
 function button(opts={}){const treatment=['toolbar','composer','outlined','outlined-primary','primary','dark'].includes(opts.variant)?opts.variant:'';const configuration=treatment?(['primary','outlined-primary'].includes(treatment)&&opts.icon?treatment+'-icon':treatment):(opts.icon?'main':'label-only');return '<button type="button" class="titan-button'+(['toolbar','composer','outlined','outlined-primary','primary','dark'].includes(opts.variant)?' titan-button--'+opts.variant:'')+'" data-inspector-variant="'+configuration+'" data-action="main"'+disabled(opts.disabled)+'>'+(opts.icon?'<span class="titan-button__icon">'+icon(opts.icon,opts.iconColor)+'</span>':'')+'<span>'+label(opts.label)+'</span></button>';}
 function halfButton(opts={}){if(!['left','right'].includes(opts.side))throw Error('A half button requires a left or right side');if(opts.size!==undefined&&!['default','composer'].includes(opts.size))throw Error('Supported half button sizes: default, composer');if(opts.labelHidden&&!opts.icon)throw Error('An icon-only half button requires an icon');const name=label(opts.label);return '<button type="button" class="titan-half-button titan-half-button--'+opts.side+(opts.size==='composer'?' titan-half-button--composer':'')+'" data-action="'+(opts.side==='left'?'main':'secondary')+'" '+(opts.labelHidden?'aria-label="'+name+'" title="'+name+'"':'')+(opts.haspopup?' aria-haspopup="'+esc(opts.haspopup)+'"':'')+(typeof opts.expanded==='boolean'?' aria-expanded="'+opts.expanded+'"':'')+disabled(opts.disabled)+'>'+(opts.icon?'<span class="titan-half-button__icon">'+icon(opts.icon,opts.iconColor)+'</span>':'')+(opts.labelHidden?'':'<span class="titan-half-button__label">'+name+'</span>')+'</button>';}
 function splitButton(opts={}){const size=opts.variant==='composer'?'composer':undefined;return '<div class="titan-split-button'+(size?' titan-split-button--composer':'')+'" role="group" aria-label="'+label(opts.label)+'">'+halfButton({side:'left',label:opts.label,icon:opts.icon,iconColor:opts.iconColor,disabled:opts.disabled,size})+halfButton({side:'right',label:opts.secondaryLabel,labelHidden:true,icon:opts.secondaryIcon||'chevron-down',iconColor:'currentColor',haspopup:opts.secondaryHaspopup===undefined?'menu':opts.secondaryHaspopup,expanded:opts.secondaryExpanded,disabled:opts.disabled||opts.secondaryDisabled,size})+'</div>';}
 function actionGroup(o={}){if(!Array.isArray(o.items)||!o.items.length)throw Error('Actions required');return '<div class="titan-action-group" role="group" aria-label="'+label(o.label)+'">'+o.items.map((item,index)=>'<span class="titan-action-group__item" data-action="'+esc(item.id??index)+'">'+button({...item,variant:'toolbar'})+'</span>').join('')+'</div>';}
 function footerActions(o={}){
 if(!Array.isArray(o.items)||!o.items.length||o.items.length>3)throw Error('Footer actions take one to three items');
 return '<div class="titan-footer-actions" data-inspector-variant="'+['','one','two','three'][o.items.length]+'" role="group" aria-label="'+label(o.label)+'">'+o.items.map((item,index)=>{
  if(!item.icon)throw Error('Each footer action requires an icon');
  const name=label(item.label);
  const hidden=o.items.length===3?index===2:!!item.labelHidden;
  const visible=hidden?'':'<span class="titan-footer-actions__label">'+name+'</span>';
  return '<button type="button" class="titan-footer-actions__item'+(hidden?' titan-footer-actions__item--icon-only':'')+'" title="'+name+'" data-action="'+esc(item.id??index)+'"'+(hidden?' aria-label="'+name+'"':'')+(item.disabled?' disabled':'')+'><span class="titan-footer-actions__icon">'+icon(item.icon,item.iconColor??'currentColor')+'</span>'+visible+'</button>';
 }).join('')+'</div>';
}
function mount(host,kind,opts={},actions={}){const render={iconButton,button,splitButton,halfButton,actionGroup,footerActions}[kind];if(!render)throw Error('Unknown action component');host.innerHTML=render(opts);const controls=kind==='actionGroup'?host.querySelectorAll('.titan-action-group__item'):host.querySelectorAll('[data-action]');controls.forEach(control=>{const controlButton=control.matches?.('button')?control:control.querySelector?.('button')||control;control.addEventListener('click',event=>{if(!controlButton.disabled)actions[control.dataset.action]?.(event);});});return host.firstElementChild;}
 return {iconButton,button,splitButton,halfButton,actionGroup,footerActions,mount};
});
