(function(root,factory){const api=typeof module==='object'&&module.exports?factory(require('./actions'),require('./selection')):factory(root.TitanActions,root.TitanSelection);if(typeof module==='object'&&module.exports)module.exports=api;else root.TitanComposer=api;})(typeof globalThis!=='undefined'?globalThis:this,function(A,S){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const files={"figma-ic-list.svg":"list","ic-delete.svg":"delete","ic-minimize.svg":"minimize","figma-ic-colors.svg":"colors","figma-ic-indent.svg":"indent","figma-ic-align.svg":"align","text-styling.svg":"text-styling","reminder.svg":"reminder","emoji.svg":"emoji","campaign.svg":"campaign","ic-ai-write.svg":"ai-write","figma-ic-link.svg":"more-vertical","ic-close.svg":"close","figma-ic-bold.svg":"bold","ic-groups.svg":"groups","signature.svg":"signature","figma-ic-underline.svg":"underline","figma-ic-italic.svg":"italic","image.svg":"image","ic-expand.svg":"expand","figma-ic-delete.svg":"delete","ic-design.svg":"design","attachment.svg":"attachment","figma-ic-more.svg":"link","drive.svg":"composer-drive","bookings.svg":"composer-bookings","html.svg":"html","ic-templates.svg":"templates","ic-invoices.svg":"invoices","ic-track.svg":"track"};
const command=(id,html)=>'<span class="titan-composer-command" data-command="'+esc(id)+'">'+html+'</span>';
const icon=(id,file,variant='composer')=>command(id,A.iconButton({label:id,icon:files[file],variant,iconSize:variant==='dark'?18:undefined,iconColor:variant==='dark'?'currentColor':undefined}));
function fieldRow(o={}){if(!o.label?.trim())throw Error('Field label required');return '<div class="titan-composer-field"><label><span>'+esc(o.label)+':</span>'+(o.readOnly?'<span class="titan-composer-field__value">'+esc(o.value)+'</span>':'<input '+(o.id?'id="'+esc(o.id)+'" ':'')+'aria-label="'+esc(o.label)+'" value="'+esc(o.value||'')+'" autocomplete="off">')+'</label>'+(o.recipient?'<div class="titan-composer-field__extras">'+['Cc','Bcc'].map(name=>command(name,A.button({label:name,variant:'composer'}))).join('')+'</div>':'')+'</div>';}
function formattingToolbar(){return '<div class="titan-formatting-toolbar" role="group" aria-label="Text formatting">'+S.dropdown({label:'Sans Serif',variant:'composer'})+'<span class="titan-formatting-toolbar__separator" aria-hidden="true"></span>'+S.dropdown({label:'14',variant:'composer'})+'<span class="titan-formatting-toolbar__separator" aria-hidden="true"></span>'+[['Bold','bold'],['Italic','italic'],['Underline','underline'],['Text color','colors'],['Alignment','align'],['Lists','list'],['Indent','indent'],['Link','more'],['More','link']].map(([label,file])=>icon(label,'figma-ic-'+file+'.svg')).join('')+'</div>';}
function composerHeader(o={}){return '<header class="titan-composer-header"><button class="titan-composer-header__title" type="button" data-command="Minimize">'+esc(o.title||'New email')+'</button><div class="titan-composer-header__actions">'+icon('Minimize','ic-minimize.svg','dark')+icon('Expand','ic-expand.svg','dark')+icon('Close','ic-close.svg','dark')+'</div></header>';}
function composerTools(){return '<div class="titan-composer-tools" role="group" aria-label="Compose tools">'+[['Track','track'],['Design','design'],['AI Write','ai-write'],['Templates','templates'],['Invoices','invoices'],['Groups','groups']].map(([label,file])=>command(label,A.button({label,icon:files['ic-'+file+'.svg'],variant:'composer'}))).join('')+'</div>';}
function composerSendActions(){return '<div class="titan-composer-send-actions" role="group" aria-label="Send and insert">'+A.splitButton({label:'Send',secondaryLabel:'Send options',variant:'composer'})+icon('Campaign','campaign.svg')+icon('Reminder','reminder.svg')+icon('Text styling','text-styling.svg')+icon('Attachment','attachment.svg')+icon('Drive','drive.svg')+icon('Image','image.svg')+icon('Emoji','emoji.svg')+icon('Signature','signature.svg')+icon('Bookings','bookings.svg')+icon('HTML','html.svg')+'<span class="titan-composer-send-actions__spacer"></span>'+icon('Discard','figma-ic-delete.svg')+'</div>';}
function emailComposer(o={}){return '<section class="titan-email-composer'+(o.docked?' composer-window titan-bottom-docked-panel':'')+'"'+(o.id?' id="'+esc(o.id)+'"':'')+' aria-label="Email composer">'+composerHeader({title:o.title})+'<div class="titan-email-composer__content"><div class="titan-email-composer__fields">'+fieldRow({label:'From',value:o.from||'alex@example.com',readOnly:true})+fieldRow({label:'To',id:o.toId,recipient:true})+fieldRow({label:'Subject'})+'</div>'+composerTools()+'<div class="titan-email-composer__editor" contenteditable="true" role="textbox" aria-label="Message body" aria-multiline="true" spellcheck="true"></div>'+formattingToolbar()+composerSendActions()+'</div></section>';}
function mount(host,kind,o={},callbacks={}){const render={fieldRow,formattingToolbar,composerHeader,composerTools,composerSendActions,emailComposer}[kind];if(!render)throw Error('Unknown composer part');host.innerHTML=render(o);const el=host.firstElementChild;const click=e=>{const button=e.target.closest('button');if(!button||button.disabled)return;const command=button.closest('[data-command]')?.dataset.command||button.dataset.action||button.textContent.trim();if(kind==='emailComposer'&&command==='Minimize'){el.classList.toggle('comp-minimized');callbacks.minimize?.(el.classList.contains('comp-minimized'));}else if(kind==='emailComposer'&&command==='Close'){if(o.docked)el.classList.remove('comp-open','comp-minimized');callbacks.close?.();}else callbacks.action?.(command,e);};el.addEventListener('click',click);return ()=>el.removeEventListener('click',click);}
return {fieldRow,formattingToolbar,composerHeader,composerTools,composerSendActions,emailComposer,mount};
});
