(function(root,factory){const api=factory(typeof module==='object'&&module.exports?require('./actions'):root.TitanActions,typeof module==='object'&&module.exports?require('./avatar'):root.TitanAvatar,typeof module==='object'&&module.exports?require('./selection'):root.TitanSelection);if(typeof module==='object'&&module.exports)module.exports=api;else root.TitanMessages=api;})(typeof globalThis!=='undefined'?globalThis:this,function(Actions,Avatar,Selection){
'use strict';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function required(value){if(typeof value!=='string'||!value.trim())throw Error('A sender is required');return esc(value);}
function row(o={}){if(o.variant&&!['stacked','wide'].includes(o.variant))throw Error('Supported row variants: stacked, wide');const sender=required(o.sender);const checkbox=Selection.checkbox({label:'Select message from '+o.sender,checked:!!o.checked});const star=Actions.iconButton({label:'Star message from '+o.sender,icon:'star-outline',pressedIcon:'star',iconColor:'currentColor',variant:'toggle',pressed:!!o.starred});return `<article class="email-tile titan-message-row${o.variant==='wide'?' titan-message-row--wide':''}${o.selected?' selected':''}" data-message-id="${esc(o.id)}"><div class="email-tile-inner"><div class="tile-icons"><label class="tile-chk">${checkbox}</label><span class="titan-message-row__indicator">${o.unread?'<span class="tile-dot" aria-label="Unread"></span>':''}<span class="titan-message-row__star" data-message-action="star">${star}</span></span></div><button type="button" class="tile-content titan-message-row__open" data-message-action="open"${o.selected?' aria-current="true"':''}><span class="tile-top"><span class="tile-sender${o.unread?' bold':''}">${sender}</span><span class="tile-time">${esc(o.time)}</span></span><span class="tile-subject">${esc(o.subject)}</span><span class="tile-preview">${esc(o.preview)}</span></button></div></article>`;}
function list(o={}){if(o.variant&&!['stacked','wide'].includes(o.variant))throw Error('Supported list variants: stacked, wide');return `<div class="email-list titan-message-list${o.variant==='wide'?' titan-message-list--wide':''}" aria-label="${esc(o.label||'Messages')}">${(o.messages||[]).map(message=>row({...message,variant:o.variant})).join('')}</div>`;}
function actionWrap(id,html){return '<span class="titan-message-card__action" data-message-action="'+esc(id)+'">'+html+'</span>';}
function actionButton(a){return actionWrap(a.id,Actions.button(a));}
function card(o={}){const sender=required(o.sender);if(o.variant&&!['collapsed','expanded'].includes(o.variant))throw Error('Supported card variants: collapsed, expanded');if(o.variant==='collapsed')return `<article class="thread-tile titan-message-card" data-message-id="${esc(o.id)}"><button type="button" class="thread-tile-inner titan-message-card__open" data-message-action="expand" aria-label="Open message from ${sender}"><span class="thread-sender">${sender}</span><span class="thread-preview">${esc(o.preview)}</span><span class="thread-meta"><span class="thread-date">${esc(o.time)}</span></span></button></article>`;
return `<article class="expanded-tile titan-message-card" data-message-id="${esc(o.id)}"><header class="expanded-header"><div class="exp-left">${o.initials?'<span class="exp-avatar">'+Avatar.render({initials:o.initials,decorative:true})+'</span>':''}<div><div class="exp-sender">${sender}</div>${o.recipients?`<div class="exp-to">${esc(o.recipients)}</div>`:''}</div></div><div class="exp-right"><span class="exp-timestamp">${esc(o.time)}</span>${o.headerActions?.length?'<div class="exp-actions">'+o.headerActions.map(a=>actionWrap(a.id,Actions.iconButton({label:a.label,icon:a.icon,variant:'compact',disabled:a.disabled}))).join('')+'</div>':''}</div></header><div class="expanded-body">${(o.paragraphs||[]).map(p=>`<p>${esc(p)||'&nbsp;'}</p>`).join('')}</div>${o.actions?.length?'<div class="expanded-footer-hr"></div><footer class="expanded-footer">'+o.actions.map(actionButton).join('')+'</footer>':''}</article>`;}
function bind(host,handlers={}){const click=event=>{const control=event.target.closest('[data-message-action]');if(!control||!host.contains(control)||control.disabled)return;const item=control.closest('[data-message-id]'),action=control.dataset.messageAction;if(action==='star'){const button=control.matches?.('button')?control:control.querySelector?.('button')||control;const pressed=button.getAttribute('aria-pressed')!=='true';button.setAttribute('aria-pressed',String(pressed));handlers.star?.(item.dataset.messageId,pressed,event);}else handlers[action]?.(item.dataset.messageId,event);};const change=event=>{if(event.target.matches('.tile-chk input'))handlers.check?.(event.target.closest('[data-message-id]').dataset.messageId,event.target.checked,event);};host.addEventListener('click',click);host.addEventListener('change',change);return ()=>{host.removeEventListener('click',click);host.removeEventListener('change',change);};}
function mount(host,kind,options,handlers){const render={row,list,card}[kind];if(!render)throw Error('Unknown message component');host.innerHTML=render(options);return bind(host,handlers);}
return {row,list,card,bind,mount};
});
