(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TitanSelection=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
const Icons=typeof module==='object'&&module.exports?require('../icons/runtime.js'):globalThis.TitanIcons;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const label=v=>{if(typeof v!=='string'||!v.trim())throw Error('Label required');return esc(v);};
 function tab(o={}){const variant=o.variant||'filled';if(!['filled','underline'].includes(variant))throw Error('Unsupported tab variant');if(!o.id)throw Error('Tab id required');return '<button type="button" class="titan-tab titan-tab--'+variant+'" role="tab" data-inspector-variant="'+variant+'" data-value="'+esc(o.id)+'" aria-selected="'+!!o.selected+'" tabindex="'+(o.tabIndex??(o.selected?0:-1))+'"'+(o.panel?' aria-controls="'+esc(o.panel)+'"':'')+'>'+label(o.label)+(o.count!=null?' ('+esc(o.count)+')':'')+'</button>';}
 function tabs(o={}){if(!o.items?.length)throw Error('Tabs require items');if(new Set(o.items.map(t=>t.id)).size!==o.items.length)throw Error('Duplicate tab ids');const active=o.value??o.items[0].id;if(!o.items.some(t=>t.id===active))throw Error('Unknown selected tab');return '<div class="titan-tabs" role="tablist" aria-label="'+label(o.label)+'">'+o.items.map(t=>tab({...t,variant:o.variant||'filled',selected:t.id===active})).join('')+'</div>';}
 function mountTabs(host,kind,o,callbacks){let props={...o};host.innerHTML=kind==='tab'?tab(props):tabs(props);const el=host.firstElementChild;const controlled=kind==='tab'||Object.prototype.hasOwnProperty.call(o,'value');
 const update=next=>{props={...props,...next};if(kind==='tab'){el.setAttribute('aria-selected',String(!!props.selected));el.tabIndex=props.tabIndex??(props.selected?0:-1);}else{if(!props.items.some(t=>t.id===props.value))throw Error('Unknown selected tab');el.querySelectorAll('[role=tab]').forEach(t=>{t.setAttribute('aria-selected',String(t.dataset.value===props.value));t.tabIndex=t.dataset.value===props.value?0:-1;});}};
 const click=e=>{const t=e.target.closest('[role=tab]');if(!t||!el.contains(t))return;if(kind==='tab')callbacks.activate?.(t.dataset.value);else{if(!controlled)update({value:t.dataset.value});callbacks.change?.(t.dataset.value);}};
 const key=e=>{if(kind!=='tabs'||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const items=[...el.querySelectorAll('[role=tab]')],i=items.indexOf(e.target);if(i<0)return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowRight'?1:-1)+items.length)%items.length;items[next].focus();items[next].click();};
 el.addEventListener('click',click);el.addEventListener('keydown',key);const cleanup=()=>{el.removeEventListener('click',click);el.removeEventListener('keydown',key);};cleanup.update=update;return cleanup;}
 function dropdown(o={}){if(o.variant==='search'){return '<button type="button" class="titan-dropdown-trigger titan-dropdown-trigger--search" data-inspector-variant="search" aria-label="'+label(o.label)+'" aria-haspopup="menu" aria-expanded="'+!!o.expanded+'"'+(o.disabled?' disabled':'')+'><svg data-titan-icon="chevron-down" viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><use href="'+Icons.resolve('chevron-down')+'#titan-artwork"></use></svg></button>';}if(o.variant==='account'||o.variant==='account-light'){return '<button type="button" class="titan-dropdown-trigger titan-dropdown-trigger--'+o.variant+'" data-inspector-variant="'+o.variant+'" aria-haspopup="menu" aria-expanded="'+!!o.expanded+'"><span class="titan-dropdown-trigger__label">'+label(o.label)+'</span><svg data-titan-icon="chevron-down" viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><use href="'+Icons.resolve('chevron-down')+'#titan-artwork"></use></svg></button>';}if(o.variant==='app-switcher'){if(!o.icon)throw Error('Icon required');return '<button type="button" class="titan-dropdown-trigger titan-dropdown-trigger--app"'+(o.controls?' aria-controls="'+esc(o.controls)+'"':'')+' aria-label="'+label(o.label)+'" aria-haspopup="dialog" aria-expanded="'+!!o.expanded+'">'+Icons.render(o.icon)+'<span class="titan-dropdown-chevron"><svg data-titan-icon="chevron-down" viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><use href="'+Icons.resolve('chevron-down')+'#titan-artwork"></use></svg></span></button>';}return '<button type="button" class="titan-dropdown-trigger'+(o.variant==='composer'?' titan-dropdown-trigger--composer':'')+'" aria-haspopup="menu" aria-expanded="'+!!o.expanded+'">'+label(o.label)+'<svg aria-hidden="true" width="10" height="10" viewBox="0 0 10 10"><path d="M0 3h10L5 8z" fill="currentColor"/></svg></button>';}
 const CHECKBOX_SIZES={'default':'','large':' titan-checkbox--large'};
 function checkbox(o={}){const size=o.size||'default';if(!(size in CHECKBOX_SIZES))throw Error('Unsupported checkbox size: '+size);return '<input class="titan-checkbox'+CHECKBOX_SIZES[size]+'" type="checkbox" aria-label="'+label(o.label)+'"'+(o.checked?' checked':'')+'>';}
 function mount(host,kind,o={},callbacks={}){if(kind==='tab'||kind==='tabs')return mountTabs(host,kind,o,callbacks);const render={tabs,dropdown,checkbox}[kind];if(!render)throw Error('Unknown selection control');host.innerHTML=render(o);const el=host.firstElementChild;const click=e=>{if(kind==='tabs'){const t=e.target.closest('[role=tab]');if(!t)return;el.querySelectorAll('[role=tab]').forEach(b=>{b.setAttribute('aria-selected',String(b===t));b.tabIndex=b===t?0:-1;});callbacks.change?.(t.dataset.value);}else if(kind==='dropdown')callbacks.open?.(e);};const change=e=>callbacks.change?.(e.target.checked);const key=e=>{if(kind!=='tabs'||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const items=[...el.querySelectorAll('[role=tab]')],i=items.indexOf(e.target);const next=e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowRight'?1:-1)+items.length)%items.length;items[next].focus();items[next].click();};el.addEventListener('click',click);el.addEventListener('keydown',key);if(kind==='checkbox')el.addEventListener('change',change);return ()=>{el.removeEventListener('click',click);el.removeEventListener('keydown',key);el.removeEventListener('change',change);};}
 return {tab,tabs,dropdown,checkbox,mount};
});
